AWSTemplateFormatVersion: '2010-09-09'
Description: 'Frontend infrastructure for Queens Solver with custom domain'

Parameters:
    DomainName:
        Type: String
        Default: jamesgarner.me
        Description: The domain name to use for the application

    CertificateArn:
        Type: String
        Description: ARN of the SSL certificate for the domain (must be in us-east-1 for CloudFront)

Resources:
    QueensSolverBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub ${AWS::StackName}-frontend
            # Remove public access configuration since we're using OAI
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: index.html

    QueensSolverBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref QueensSolverBucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Sid: AllowCloudFrontAccess
                      Effect: Allow
                      Principal:
                          CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
                      Action: 's3:GetObject'
                      Resource: !Join ['', [!GetAtt QueensSolverBucket.Arn, '/*']]

    QueensSolverDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Enabled: true
                DefaultRootObject: index.html
                Aliases:
                    - !Ref DomainName
                    - !Sub www.${DomainName}
                Origins:
                    - DomainName: !GetAtt QueensSolverBucket.RegionalDomainName
                      Id: S3Origin
                      S3OriginConfig:
                          OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
                DefaultCacheBehavior:
                    TargetOriginId: S3Origin
                    ViewerProtocolPolicy: redirect-to-https
                    AllowedMethods:
                        - GET
                        - HEAD
                    CachedMethods:
                        - GET
                        - HEAD
                    ForwardedValues:
                        QueryString: false
                        Cookies:
                            Forward: none
                CacheBehaviors:
                    - PathPattern: '/queens-solver/*'
                      TargetOriginId: S3Origin
                      ViewerProtocolPolicy: redirect-to-https
                      AllowedMethods:
                          - GET
                          - HEAD
                      CachedMethods:
                          - GET
                          - HEAD
                      ForwardedValues:
                          QueryString: false
                          Cookies:
                              Forward: none
                      ResponseHeadersPolicyId: !Ref QueensSolverResponseHeadersPolicy
                CustomErrorResponses:
                    - ErrorCode: 403
                      ResponsePagePath: /queens-solver/index.html
                      ResponseCode: 200
                    - ErrorCode: 404
                      ResponsePagePath: /queens-solver/index.html
                      ResponseCode: 200
                ViewerCertificate:
                    AcmCertificateArn: !Ref CertificateArn
                    SslSupportMethod: sni-only
                    MinimumProtocolVersion: TLSv1.2_2021

    CloudFrontOriginAccessIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: !Sub ${AWS::StackName}-OAI

    # Route 53 Records
    HostedZone:
        Type: AWS::Route53::HostedZone
        Properties:
            Name: !Ref DomainName

    DomainRecord:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref HostedZone
            Name: !Ref DomainName
            Type: A
            AliasTarget:
                DNSName: !GetAtt QueensSolverDistribution.DomainName
                HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID (constant)
                EvaluateTargetHealth: false

    WwwDomainRecord:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: !Ref HostedZone
            Name: !Sub www.${DomainName}
            Type: A
            AliasTarget:
                DNSName: !GetAtt QueensSolverDistribution.DomainName
                HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID (constant)
                EvaluateTargetHealth: false

    QueensSolverResponseHeadersPolicy:
        Type: AWS::CloudFront::ResponseHeadersPolicy
        Properties:
            ResponseHeadersPolicyConfig:
                Name: !Sub ${AWS::StackName}-response-headers-policy
                Comment: 'Response headers policy for Queens Solver application'
                CorsConfig:
                    AccessControlAllowOrigins:
                        Items: ['*']
                    AccessControlAllowHeaders:
                        Items: ['*']
                    AccessControlAllowMethods:
                        Items: ['GET', 'HEAD', 'OPTIONS']
                    AccessControlMaxAgeSec: 600
                    OriginOverride: false
                    AccessControlAllowCredentials: false
                CustomHeadersConfig:
                    Items:
                        - Header: Content-Type-Options
                          Value: nosniff
                          Override: true
                        - Header: X-Frame-Options
                          Value: SAMEORIGIN
                          Override: true

Outputs:
    BucketName:
        Description: Name of S3 bucket
        Value: !Ref QueensSolverBucket
    CloudFrontURL:
        Description: URL for website hosted on CloudFront
        Value: !Sub https://${QueensSolverDistribution.DomainName}
    CloudFrontDistributionId:
        Description: ID of the CloudFront distribution
        Value: !Ref QueensSolverDistribution
    DomainURL:
        Description: Custom domain URL
        Value: !Sub https://${DomainName}/queens-solver
    HostedZoneId:
        Description: ID of the Route 53 hosted zone
        Value: !Ref HostedZone
    NameServers:
        Description: Nameservers for the hosted zone
        Value: !Join [', ', !GetAtt HostedZone.NameServers]
